# Generated by Django 4.1.3 on 2022-11-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAI',
            new_name='AIPost',
        ),
    ]
