# Generated by Django 4.1.3 on 2022-11-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_aipost_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipost',
            name='corectness',
        ),
    ]
