# Generated by Django 4.1.3 on 2023-01-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aipost_options_aipost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipost',
            name='ans1',
            field=models.TextField(blank=True, default=''),
        ),
    ]
