# Generated by Django 4.1.3 on 2023-01-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_ans1_aipost_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aipost',
            name='answer_correct',
            field=models.BooleanField(default=False),
        ),
    ]
