# Generated by Django 4.1.3 on 2023-01-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aipost_answer_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aipost',
            name='answer_correct',
        ),
    ]
